### ISSUE TITLE
Discord not launched when using canary

### ISSUE THREAD

**Issue by nikorue** [BrasileiroGamer/DeezerRPC#18]
title is self-explanatory - no activity and "rich-presence login failed, make sure discord is launched" when using canary

**Comment by nikorue** [comment]
when launching as root "Uncaught Exception: TypeError: Object has been destroyed at Object.<anonymous> (C:\..\deezerrpc\resources\app.asar\build\main.js:43:22) at Object.onceWrapper (events.js:422:26); at Object.emit (events.js:327:22)

**Comment by nikorue** [comment]
it works when launching as admin
